services:
  soraapi:
    image: thesmallhancat/sora2api:latest
    container_name: soraapi
    volumes:
      - ./data:/app/data
      - ./config/setting_warp.toml:/app/config/setting.toml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - warp
    networks:
      - warp-network
      - gateway-network

  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - warp_data:/var/lib/cloudflare-warp
    networks:
      - warp-network

networks:
  warp-network:
    external: true
  gateway-network:
    external: true

volumes:
  warp_data:
